website: http://ob-mc.net
name: OBWizardFun
author: Fahrenheit451
version: 1.0
api-version: "1.21"
main: net.obmc.OBWizardFun.OBWizardFun
description: Pesky wizards casting random spells on players
commands:
  cast:
    description: Cast a spell on a player.
    usage: Type /cast <spell> <player>