name: ${project.name}
description: ${project.description}
author: Fahrenheit451|Capri205
website: ${project.url}
version: ${project.version}
api-version: ${api-version}
main: net.obmc.${project.name}.${project.name}
commands:
  cast:
    description: Cast a spell on a player.
    usage: Type /cast <spell> <player>